/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuestionario;

import java.util.Calendar;
import javax.swing.JOptionPane;



public class ProbarCuestionario extends javax.swing.JFrame {
  static   int  correctas = 0;
static    int posicion = 0;
    int segundo=0;
    public ProbarCuestionario() {
        initComponents();
        GenerarCues p1 = new GenerarCues();
       tituloPregunta.setText(p1.getPreguntas().get(posicion).getTitulo());
       opcion1.setText(p1.getPreguntas().get(posicion).getOpcion().get(0).getTitulo());
       opcion2.setText(p1.getPreguntas().get(posicion).getOpcion().get(1).getTitulo());
       opcion3.setText(p1.getPreguntas().get(posicion).getOpcion().get(2).getTitulo());
       
        
       Thread t1= new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                               
                try{
                                      
                    segundo ++;
                    if (segundo >= 50){
                    segundo = 0;
                    posicion ++;
                    tituloPregunta.setText(p1.getPreguntas().get(posicion).getTitulo());
       opcion1.setText(p1.getPreguntas().get(posicion).getOpcion().get(0).getTitulo());
       opcion2.setText(p1.getPreguntas().get(posicion).getOpcion().get(1).getTitulo());
       opcion3.setText(p1.getPreguntas().get(posicion).getOpcion().get(2).getTitulo());
                    }
                    else{
                    tiempoRes.setText(""+segundo);
                    
                    Thread.sleep(1000);}
                }catch(InterruptedException ex){
                
                }
                }
            }
        });
    t1.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Siguiente = new javax.swing.JButton();
        opcion1 = new javax.swing.JRadioButton();
        opcion2 = new javax.swing.JRadioButton();
        opcion3 = new javax.swing.JRadioButton();
        tiempoRes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tituloPregunta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Siguiente.setText("SIGUIENTE >>");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcion1);
        opcion1.setForeground(new java.awt.Color(255, 255, 255));
        opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcion2);
        opcion2.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(opcion3);
        opcion3.setForeground(new java.awt.Color(255, 255, 255));
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });

        tiempoRes.setText("jLabel1");

        tituloPregunta.setEditable(false);
        tituloPregunta.setColumns(20);
        tituloPregunta.setLineWrap(true);
        tituloPregunta.setRows(5);
        tituloPregunta.setWrapStyleWord(true);
        tituloPregunta.setBorder(null);
        jScrollPane1.setViewportView(tituloPregunta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tiempoRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(Siguiente)
                .addGap(135, 135, 135))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion2)
                            .addComponent(opcion1)
                            .addComponent(opcion3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opcion1)
                .addGap(30, 30, 30)
                .addComponent(opcion2)
                .addGap(30, 30, 30)
                .addComponent(opcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Siguiente)
                    .addComponent(tiempoRes))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion1ActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        
        
       GenerarCues p1 = new GenerarCues();
       posicion ++;
       
       if (posicion <=9){
       
       
       tituloPregunta.setText(p1.getPreguntas().get(posicion).getTitulo());
       opcion1.setText(p1.getPreguntas().get(posicion).getOpcion().get(0).getTitulo());
       opcion2.setText(p1.getPreguntas().get(posicion).getOpcion().get(1).getTitulo());
       opcion3.setText(p1.getPreguntas().get(posicion).getOpcion().get(2).getTitulo());
       if (opcion1.isSelected()) {
       if(p1.getPreguntas().get(posicion).getOpcion().get(0).isRespuesta()){
       correctas ++;
       }
       }
       if (opcion2.isSelected()) {
       if(p1.getPreguntas().get(posicion).getOpcion().get(1).isRespuesta()){
       correctas ++;
       }
       }
       if (opcion3.isSelected()) {
       if(p1.getPreguntas().get(posicion).getOpcion().get(2).isRespuesta()){
       correctas ++;
       }
       
       }
       
       
       }
       else{
           respuestas r = new respuestas(correctas);
           r.setVisible(true);
           System.out.println(correctas);
           dispose();
           
           
       }
       buttonGroup1.clearSelection();
       segundo=0;
       
    }//GEN-LAST:event_SiguienteActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProbarCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProbarCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProbarCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProbarCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProbarCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    private javax.swing.JRadioButton opcion3;
    private javax.swing.JLabel tiempoRes;
    private javax.swing.JTextArea tituloPregunta;
    // End of variables declaration//GEN-END:variables
}
